Add dd tracing to opensearch
shopsmart/opensearchconfig-go pull request #9
Opened 2023-08-01 18:03 UTC by michaelginalick

## Problem

Trace opensearch requests

## Solution

Add datadop tracing library and wrap the opensearch client

2023-08-02 16:31 UTC, mike-carey requested changes
Can we please make this configurable via the `DD_TRACE_ENABLED` environment variable?  This is a public repo and not everyone may be using DataDog.

2023-08-02 16:31 UTC, mike-carey commented on opensearchconfig.go
> +	opensearchConfig.Transport = httptrace.WrapRoundTripper(&http.Transport{})
```suggestion
	opensearchConfig.Transport = &http.Transport{}
```

2023-08-02 16:33 UTC, mike-carey commented on opensearchconfig.go
You will need to import "os" if you accept this.

2023-08-02 17:38 UTC, mike-carey commented on opensearchconfig.go
> +	// ENV variable to controll whether traces are send to datadog
```suggestion
	// ENV variable to control whether traces are send to datadog
```

2023-08-02 17:39 UTC, mike-carey approved these changes

2023-08-02 17:39 UTC, mike-carey commented on opensearchconfig.go
> +	// Add datadog tracing
```suggestion
```

2023-08-03 16:21 UTC, andrewbatallones approved these changes

2023-08-03 16:57 UTC, merged